<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.9" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="11.3.9" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.9" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.9" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.9" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageVersion Include="DbTool.Core" Version="$(DbToolPackageVersion)" />
    <PackageVersion Include="DbTool.DbProvider.MySql" Version="$(DbToolPackageVersion)" />
    <PackageVersion Include="DbTool.DbProvider.PostgreSql" Version="$(DbToolPackageVersion)" />
    <PackageVersion Include="DbTool.DbProvider.SqlServer" Version="$(DbToolPackageVersion)" />
    <PackageVersion Include="Irihi.Ursa" Version="1.14.0" />
    <PackageVersion Include="Irihi.Ursa.Themes.Semi" Version="1.14.0" />
    <PackageVersion Include="Semi.Avalonia" Version="11.3.7.1" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.4" />
    <PackageVersion Include="WeihanLi.Common" Version="1.0.86" />
    <PackageVersion Include="WeihanLi.Extensions.Localization.Json" Version="2.0.0" />
    <PackageVersion Include="WeihanLi.Npoi" Version="3.3.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageVersion Include="xunit" Version="2.4.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>
</Project>
