<Project>
  <PropertyGroup>
		<VersionMajor>4</VersionMajor>
		<VersionMinor>1</VersionMinor>
		<VersionPatch>0</VersionPatch>
		<VersionPrefix>$(VersionMajor).$(VersionMinor).$(VersionPatch)</VersionPrefix>
		<VersionSuffix Condition="'$(Configuration)'=='DEBUG'">preview</VersionSuffix>
	</PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/WeihanLi/DbTool</RepositoryUrl>
    <Authors>DbTool Contributors</Authors>
    <Copyright>Copyright 2017-2026 (c) WeihanLi</Copyright>
  </PropertyGroup>
</Project>
