<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>DbTool</RootNamespace>
    <AssemblyName>DbTool</AssemblyName>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationIcon>DbTool.ico</ApplicationIcon>
    <DbToolPackageVersion>4.0.0</DbToolPackageVersion>
    <AvaloniaUseCompiledBindings>true</AvaloniaUseCompiledBindings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="out\**" />
    <EmbeddedResource Remove="out\**" />
    <None Remove="out\**" />
    <AvaloniaResource Remove="out\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Irihi.Ursa" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="WeihanLi.Common" />
    <PackageReference Include="WeihanLi.Extensions.Localization.Json" />
    <PackageReference Include="WeihanLi.Npoi" />
    <PackageReference Include="DbTool.Core" />
    <PackageReference Include="DbTool.DbProvider.MySql" />
    <PackageReference Include="DbTool.DbProvider.PostgreSql" />
    <PackageReference Include="DbTool.DbProvider.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\**\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
